import Relay

open Relay

-- All fixtures are PUBLIC deterministic data. This is not a random source.
private def fixtureRoot (seed : Nat) : RootBytes :=
  fun b => ⟨(seed + 17 * b.val) % 256, Nat.mod_lt _ (by decide)⟩

private def fixtureCoins (seed : Nat) : Randomness :=
  fun b a => (seed + 31 * b.val + 73 * a.val : Nat)

private def rootCSV (root : RootBytes) : String :=
  String.intercalate "," ((List.finRange 32).map fun b => toString (root b).val)

private def secretCSV (secret : Secret) : String :=
  String.intercalate "," ((List.finRange 32).map fun b => toString (secret b).val)

private def coinsCSV (coins : Randomness) : String :=
  String.intercalate "," ((List.finRange 32).flatMap fun b =>
    (List.finRange 3).map fun a => toString (coins b a).val)

private def optionalRoot (root : Option RootBytes) : String :=
  match root with
  | none => "-"
  | some value => rootCSV value

private def emitSplit (id rootSeed coinSeed : Nat) : IO Unit := do
  let root := fixtureRoot rootSeed
  let coins := fixtureCoins coinSeed
  let shares := share (encodeRoot root) coins
  let encoded := String.intercalate ";" ((List.finRange 8).map fun i => secretCSV (shares i))
  IO.println s!"S|{id}|{rootCSV root}|{coinsCSV coins}|{encoded}"

private def emitRecovery (corrupt missing : Nat) : IO Unit := do
  let root := fixtureRoot 83
  let shares := share (encodeRoot root) (fixtureCoins 2026)
  let received : Received := fun i =>
    if missing.testBit i.val then none
    else if corrupt.testBit i.val then some (fun b => shares i b + (i.val + b.val + 1 : Nat))
    else some (shares i)
  let raw := candidates received
  let canonical := raw.filterMap decodeRoot
  let unique := canonical.eraseDups
  let roots := String.intercalate ";" (unique.map rootCSV)
  let verified := recoverRoot received (fun candidate => decide (candidate = root))
  let allAccepted := recoverRoot received (fun _ => true)
  IO.println s!"R|6|{corrupt}|{missing}|{raw.length}|{raw.length - canonical.length}|{roots}|{optionalRoot verified}|{optionalRoot allAccepted}"

def main : IO Unit := do
  IO.println "# Octave Rust differential fixtures v1; PUBLIC data; generated by VectorMain.lean"
  let seeds := [0, 1, 42, 255, 256, 1024]
  for (id, seed) in seeds.zipIdx |>.map (fun (seed, id) => (id, seed)) do
    emitSplit id seed seed
  emitSplit 6 83 2026
  for present in List.range 9 do
    emitRecovery 0 (256 - 2 ^ present)
  let corruptSets := ((List.finRange 8).sublistsLen 3).map List.toFinset
  for corrupt in corruptSets do
    for offline in List.finRange 8 do
      if offline ∉ corrupt then
        let mask := ((List.finRange 8).filter (fun i => decide (i ∈ corrupt))).foldl
          (fun acc i => acc + 2 ^ i.val) 0
        emitRecovery mask (2 ^ offline.val)
